# Generated by Django 5.1.4 on 2024-12-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
        migrations.AlterModelTable(
            name='matchparticipant',
            table='matchparticipant',
        ),
    ]
