# Generated by Django 5.1.4 on 2024-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_match_table_alter_matchparticipant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
