# Generated by Django 5.1.4 on 2024-12-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_id', models.CharField(db_index=True, max_length=255)),
                ('puuid', models.CharField(db_index=True, max_length=255)),
                ('profile_icon_id', models.IntegerField()),
                ('revision_date', models.BigIntegerField()),
                ('summoner_level', models.IntegerField()),
            ],
        ),
    ]
